/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rentcar;

import java.io.File; // reconoce la palabra File, permite referenciar archivos del sistema
import java.io.FileNotFoundException; // Sin esto, el catch no funcionaría, importa la excepción que se lanza cuando el archivo no existe
import java.lang.classfile.Label;
import java.util.Scanner;
import javax.swing.*; // Importa todo lo que está dentro de javax.swing, incluyendo JOptionPane, JTextField, JPasswordField, JFrame

/**
 *
 * @author isvaa hi.
 */
public class Login extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
       initComponents(); 

    Label_Video.setIcon(new javax.swing.ImageIcon(
        getClass().getResource("/com/mycompany/rentcar/imagenes/kda.gif")
    ));
    
      Label_Azul.setIcon(new javax.swing.ImageIcon(
        getClass().getResource("/com/mycompany/rentcar/imagenes/Azul_Arriba.png")
    ));

    Label_RosadoAbajo.setIcon(new javax.swing.ImageIcon(
        getClass().getResource("/com/mycompany/rentcar/imagenes/Rosa_Abajo.png")
    ));

    Label_RosaArriba.setIcon(new javax.swing.ImageIcon(
        getClass().getResource("/com/mycompany/rentcar/imagenes/splash_rosa.png")
    ));

    Label_Logo.setIcon(new javax.swing.ImageIcon(
        getClass().getResource("/com/mycompany/rentcar/imagenes/Logo.png")
    ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label_Usuario = new javax.swing.JLabel();
        Label_Contraseña = new javax.swing.JLabel();
        TextUsuario = new javax.swing.JTextField();
        TextContraseña = new javax.swing.JPasswordField();
        BtnIngresar = new javax.swing.JButton();
        Label_Video = new javax.swing.JLabel();
        Label_Azul = new javax.swing.JLabel();
        Label_RosadoAbajo = new javax.swing.JLabel();
        Label_RosaArriba = new javax.swing.JLabel();
        Label_Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KDA RentCart | Login");
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        Label_Usuario.setText("Usuario:");

        Label_Contraseña.setText("Contraseña:");
        Label_Contraseña.setToolTipText("");

        BtnIngresar.setText("Ingresar");
        BtnIngresar.addActionListener(this::BtnIngresarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Label_Video)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Label_RosaArriba, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_Logo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Label_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Label_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Label_RosadoAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(BtnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Azul)
                .addContainerGap(624, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_Video, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Label_RosaArriba, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Logo)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Label_Azul)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Usuario)
                    .addComponent(TextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Contraseña)
                    .addComponent(TextContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_RosadoAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnIngresar)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed
        String usuario = TextUsuario.getText().trim(); // .trim() elimina espacios en blanco al inicio y al final.
        String contrasena = new String(TextContraseña.getPassword()).trim(); // getPassword() porque se esta usando un Password Field
        boolean encontrado = false; //  Indica si el usuario fue encontrado en el archivo.
        if (usuario.isEmpty() || contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese usuario y contraseña");
            return;
        }

        try { // Inicia el bloque protegido. Si algo falla adentro, el programa no se rompe sino que va al catch.
            File archivo = new File("Archivos/usuarios.txt");
            Scanner sc = new Scanner(archivo);

            sc.nextLine(); // Salta el encabezado

            while (sc.hasNextLine()) { // El método hasNextLine() devuelve verdadero si hay otra línea de texto disponible en el escáner. Repite el ciclo mientras haya más líneas en el archivo. Cada iteración procesa una fila.
                String linea = sc.nextLine(); // Lee la línea actual completa. Por ejemplo: 1,admin,123.
                String[] partes = linea.split(","); // Divide la línea en un arreglo usando la coma como separador.

                if (partes.length >= 6) {

                    String user = partes[0].trim();
                    String pass = partes[1].trim();
                    int nivel = Integer.parseInt(partes[2].trim());
                    String nombre = partes[3].trim();

                    if (user.equals(usuario) && pass.equals(contrasena)) {
                        encontrado = true;

                        JOptionPane.showMessageDialog(this, "Bienvenido " + nombre);

                        if (user.equals(usuario) && pass.equals(contrasena)) {
                            encontrado = true;
                             

                            // REQUISITO iv: Llamamos al menú pasando el nombre Y el nivel
                            // Ya no bloqueamos aquí con un mensaje, dejamos que el Menú se abra
                            // pero él mismo sabrá si desactivar el botón o no.
                            new Menu(nombre, nivel).setVisible(true);
                            this.dispose();

                            break;
                        }
                    }
                }
            }
            sc.close(); // Cierra el archivo una vez que terminó de leerlo. Siempre hay que cerrarlo para liberar recursos.

        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Archivo no encontrado.");
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.");
        }
    }//GEN-LAST:event_BtnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JLabel Label_Azul;
    private javax.swing.JLabel Label_Contraseña;
    private javax.swing.JLabel Label_Logo;
    private javax.swing.JLabel Label_RosaArriba;
    private javax.swing.JLabel Label_RosadoAbajo;
    private javax.swing.JLabel Label_Usuario;
    private javax.swing.JLabel Label_Video;
    private javax.swing.JPasswordField TextContraseña;
    private javax.swing.JTextField TextUsuario;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
